### ISSUE TITLE
python3.5 weakref exception

### ISSUE THREAD

**Issue by dkirkby** [desihub/desiconda#11] opened 2017-09-19 21:02 UTC
I encountered the following (harmless?) error running interactively on cori today:
```
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x2af1c27df378>
Traceback (most recent call last):
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```
The same code did not produce this error yesterday.

**Comment by weaverba137** [comment] 2017-09-19 22:38
I believe that is harmless, especially since the exception is being ignored.  This can be caused by memory being freed elsewhere, and then when weakref is shutting down, there's nothing left to free.  I know this sometimes happens when using `astropy.io.fits`.

**Comment by tskisner** [comment] 2017-11-30 21:50
We are now using python 3.6 and newer versions of lots of packages.  Closing this for now, but feel free to re-open if you see the same error again.

**Closed by tskisner** 2017-11-30 21:50 UTC
